[workspace]
authors = ["Maulik Madhavi <maulik.madhavi@gmail.com>"]
name = "llm-devs"
platforms = ["linux-64"]
version = "0.1.0"
channels = ["nvidia/label/cuda-12.8.0", "nvidia", "conda-forge", "pytorch"]

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.1.1,<26"
pypdf2 = ">=3.0.1,<4"
gcc = ">=15.1.0,<15.2"

[pypi-dependencies]
torch = { version = "==2.7.0+cu128", index = "https://download.pytorch.org/whl/cu128/" }
tqdm = ">=4.67.1, <5"
torchvision = { version = "==0.22.0", index = "https://download.pytorch.org/whl/cu128" }
torchaudio = { version = "==2.7.0+cu128", index = "https://download.pytorch.org/whl/cu128/" }
huggingface-hub = ">=0.30.2, <0.31"
google-generativeai = ">=0.8.5, <0.9"
langchain-community = ">=0.3.25, <0.4"
faiss-cpu = ">=1.11.0, <2"
pandas = ">=2.2.3, <3"
datasets = ">=3.6.0, <4"
librosa = ">=0.11.0, <0.12"
soundfile = ">=0.13.1, <0.14"
transformers = ">=4.52.4, <5"
evaluate = ">=0.4.3, <0.5"
jiwer = ">=3.1.0, <4"
accelerate = ">=1.7.0, <2"
tensorboard = ">=2.19.0, <3"
openai = ">=1.84.0, <2"
langchain-ollama = ">=0.3.3, <0.4"
paper-qa = { version = ">=5.21.0, <6", extras = ["local"] }
gradio = ">=5.33.0, <6"
pypdf = ">=5.6.0, <6"
chromadb = ">=1.0.12, <2"
langchain-nvidia-ai-endpoints = ">=0.3.10, <0.4"
hf-xet = ">=1.1.3, <2"
psycopg2-binary = ">=2.9.10, <3"
faker = ">=37.4.0, <38"
logfire = ">=3.19.0, <4"
langgraph = ">=0.4.8, <0.5"
duckduckgo-search = ">=8.0.4, <9"
wikipedia = ">=1.4.0, <2"
langchain-experimental = ">=0.3.4, <0.4"
neo4j = ">=5.28.1, <6"
yfiles-jupyter-graphs = ">=1.10.7, <2"
tiktoken = ">=0.9.0, <0.10"
json-repair = ">=0.46.2, <0.47"
