[workspace]
authors = ["Maulik Madhavi <maulik.madhavi@gmail.com>"]
name = "llm-devs"
platforms = ["linux-64"]
version = "0.1.0"
channels = ["nvidia/label/cuda-12.8.0", "nvidia", "conda-forge", "pytorch"]

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.1.1,<26"
pypdf2 = ">=3.0.1,<4"

[pypi-dependencies]
torch = { version = "==2.7.0+cu128", index = "https://download.pytorch.org/whl/cu128/" }
tqdm = ">=4.67.1, <5"
torchvision = { version = "==0.22.0", index = "https://download.pytorch.org/whl/cu128" }
torchaudio = { version = "==2.7.0+cu128", index = "https://download.pytorch.org/whl/cu128/" }
huggingface-hub = ">=0.30.2, <0.31"
google-generativeai = ">=0.8.5, <0.9"
langchain = ">=0.3.25, <0.4"
langchain-community = ">=0.3.23, <0.4"
faiss-cpu = ">=1.11.0, <2"
pandas = ">=2.2.3, <3"
datasets = ">=3.6.0, <4"
librosa = ">=0.11.0, <0.12"
soundfile = ">=0.13.1, <0.14"
transformers = ">=4.52.2, <5"
evaluate = ">=0.4.3, <0.5"
jiwer = ">=3.1.0, <4"
accelerate = ">=1.7.0, <2"
tensorboard = ">=2.19.0, <3"
openai = ">=1.84.0, <2"
