[workspace]
authors = ["Maulik Madhavi <maulik.madhavi@gmail.com>"]
channels = ["conda-forge"]
name = "llm-devs"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pip = ">=25.1.1,<26"

[pypi-dependencies]
huggingface-hub = ">=0.30.2, <0.31"
google-generativeai = ">=0.8.5, <0.9"
